DROP DATABASE IF EXISTS syncxplus;
CREATE DATABASE syncxplus;

use syncxplus;

DROP TABLE IF EXISTS image;
CREATE TABLE image (
  id INT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  url TEXT,
  PRIMARY KEY (id)
);
